# pnpm workspace configuration
# Overrides force all packages to use specific dependency versions
# This prevents security vulnerabilities and ensures consistent versions across the project
overrides:
  # Force esbuild to 0.25.0+ (bypasses any package requesting <=0.24.2)
  # Reason: Security vulnerability in esbuild <=0.24.2
  esbuild@<=0.24.2: '>=0.25.0'
